# 海康互联测试接口

### 获取应用Token
GET http://127.0.0.1:8080/hikiot/token

### 刷新应用Token（需先获取应用token）
POST http://127.0.0.1:8080/hikiot/token/refresh

### 获取用户Token
GET http://127.0.0.1:8080/hikiot/user/token

### 刷新用户Token（需先获取用户token）
POST http://127.0.0.1:8080/hikiot/user/token/refresh

### 清空所有token
GET http://127.0.0.1:8080/hikiot/clean

### 获取非设备Token
GET http://127.0.0.1:8080/hikiot/ops/token

### 获取资源详情（指定设备序列号和通道号）
GET http://127.0.0.1:8080/hikiot/resource?deviceSerial=GU0609982&channelNo=1

### 获取设备Token（指定设备序列号和通道号）
GET http://127.0.0.1:8080/hikiot/device/token?deviceSerial=GU0609982&channelNo=1

### 获取设备能力集（指定设备序列号和通道号）
GET http://127.0.0.1:8080/hikiot/device/capacity?deviceSerial=GU0609982&channelNo=1

### 获取所有设备（默认每页50条）
GET http://127.0.0.1:8080/hikiot/device/list

### 获取设备分页（指定页码和大小）
GET http://127.0.0.1:8080/hikiot/device/page?page=1&size=20

