server:
   port: 8080

hikiot:
  app-key: 2076543337980309596
  app-secret: ss5eyi/j3YDMUnIvG7Tuq9W8dOzKa0RzW5w03g==
  user-name: 13998417419
  password: 123456
  redirect-url: http://mobile.njher.com/agriculture/hikiot/callback
